repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: 1password
    url: https://1password.github.io/connect-helm-charts/
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: damoun
    url: https://damoun.github.io/helm-charts/

templates:
  default:
    missingFileHandler: Warn
    values:
      - config/{{`{{ .Release.Name }}`}}/values.yaml
  raw:
    dependencies:
      - chart: incubator/raw
        version: x.x.x

releases:
  - name: connect
    namespace: 1password
    chart: 1password/connect
    set:
      - name: connect.credentials
        file: 1password-credentials.json
      - name: operator.create
        value: true
      - name: operator.token.value
        file: 1password-access-token.txt
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: 19.7.2
    inherit:
      - template: default
      - template: raw
    needs:
      - 1password/connect
      - monitoring/prometheus-operator-crds
  - name: transmission
    namespace: torrent
    chart: damoun/transmission
    inherit:
      - template: default
      - template: raw
  - name: home-assistant
    namespace: home-automation
    chart: damoun/home-assistant
    inherit:
      - template: default
  - name: gickup
    namespace: backup
    chart: damoun/gickup
    version: 1.x.x
    inherit:
      - template: default
      - template: raw
    needs:
      - 1password/connect
  - name: blackbox-exporter
    namespace: monitoring
    chart: prometheus-community/prometheus-blackbox-exporter
    version: 7.6.x
    inherit:
      - template: default
    needs:
      - monitoring/prometheus-operator-crds
  - name: proxmox-exporter
    namespace: monitoring
    chart: damoun/proxmox-exporter
    version: 1.x.x
    inherit:
      - template: default
    needs:
      - 1password/connect
      - monitoring/prometheus-operator-crds
