repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: 1password
    url: https://1password.github.io/connect-helm-charts/
  - name: damoun
    url: https://damoun.github.io/helm-charts/

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: 19.7.2
    values:
      - prometheus.yaml
  - name: transmission
    namespace: torrent
    chart: damoun/transmission
    values: 
      - transmission.yaml
  - name: home-assistant
    namespace: home-automation
    chart: damoun/home-assistant
    values: [home-assistant.yaml]
  - name: connect
    namespace: 1password
    chart: 1password/connect
    set:
      - name: connect.credentials
        file: 1password-credentials.json
      - name: operator.create
        value: true
      - name: operator.token.value
        file: 1password-access-token.txt
  - name: gickup
    namespace: backup
    chart: damoun/gickup
    values:
      - gickup.yaml
