apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  labels:
    app: transmission

spec:
  selector:
    app: transmission
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: p2p
      protocol: TCP
      port: 51413
      targetPort: p2p
    - name: p2p-udp
      protocol: UDP
      port: 51413
      targetPort: p2p-udp
  type: ClusterIP
